# Generated by Django 5.2.13 on 2026-05-09 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinishingKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("name_uk", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Finishing Kind",
                "verbose_name_plural": "Finishing Kind",
                "db_table": "finishing_kind",
            },
        ),
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("name_uk", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "form_factor",
                    models.CharField(
                        choices=[("sheet", "Sheet"), ("roll", "Roll"), ("other", "Other")],
                        db_index=True,
                        default="sheet",
                        max_length=16,
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=100)),
            ],
            options={
                "verbose_name": "Material category",
                "verbose_name_plural": "Material categories",
                "db_table": "material_categories",
                "ordering": ["sort_order", "name_uk"],
            },
        ),
        migrations.CreateModel(
            name="OperationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("name_uk", models.CharField(max_length=255)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("print", "Print"),
                            ("finishing", "Finishing"),
                            ("cutting", "Cutting"),
                            ("assembly", "Assembly"),
                            ("service", "Service"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("handler_code", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("requires_setup", models.BooleanField(default=False)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=100)),
            ],
            options={
                "verbose_name": "Operation type",
                "verbose_name_plural": "Operation types",
                "db_table": "operation_types",
                "ordering": ["group", "sort_order", "name_uk"],
            },
        ),
        migrations.CreateModel(
            name="ProductKindName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("name_uk", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Product kind name",
                "verbose_name_plural": "Product kind names",
                "db_table": "product_kind_names",
            },
        ),
        migrations.CreateModel(
            name="ProductTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("name_uk", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=100)),
                ("allowed_material_categories_json", models.JSONField(blank=True, default=list)),
                ("parameter_schema_json", models.JSONField(blank=True, default=dict)),
                ("ui_schema_json", models.JSONField(blank=True, default=dict)),
                ("route_profile", models.CharField(blank=True, default="", max_length=64)),
                ("pricing_profile", models.CharField(blank=True, default="", max_length=64)),
            ],
            options={
                "verbose_name": "Product template",
                "verbose_name_plural": "Product templates",
                "db_table": "product_templates",
                "ordering": ["sort_order", "name_uk"],
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("name_uk", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=100)),
            ],
            options={
                "verbose_name": "Product type",
                "verbose_name_plural": "Product types",
                "db_table": "product_types",
                "ordering": ["sort_order", "name_uk"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("name_uk", models.CharField(max_length=255)),
                (
                    "form_factor",
                    models.CharField(
                        choices=[("sheet", "Sheet"), ("roll", "Roll"), ("other", "Other")],
                        db_index=True,
                        default="sheet",
                        max_length=16,
                    ),
                ),
                ("density_gsm", models.PositiveIntegerField(blank=True, null=True)),
                ("thickness_um", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "width_mm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "height_mm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("vendor_name", models.CharField(blank=True, default="", max_length=255)),
                ("is_printable", models.BooleanField(db_index=True, default=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="catalog.materialcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materials",
                "db_table": "materials",
                "ordering": ["name_uk"],
            },
        ),
        migrations.CreateModel(
            name="MaterialOperationCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_allowed", models.BooleanField(db_index=True, default=True)),
                ("priority", models.PositiveIntegerField(db_index=True, default=100)),
                ("constraints_json", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_capabilities",
                        to="catalog.material",
                    ),
                ),
                (
                    "operation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_capabilities",
                        to="catalog.operationtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material operation capability",
                "verbose_name_plural": "Material operation capabilities",
                "db_table": "material_operation_capabilities",
                "ordering": ["material_id", "priority", "operation_type_id"],
            },
        ),
        migrations.CreateModel(
            name="ProductTemplateOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_required", models.BooleanField(db_index=True, default=False)),
                ("is_optional", models.BooleanField(db_index=True, default=True)),
                ("default_enabled", models.BooleanField(default=False)),
                ("sequence_order", models.PositiveIntegerField(db_index=True, default=100)),
                ("constraints_json", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "operation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_operations",
                        to="catalog.operationtype",
                    ),
                ),
                (
                    "product_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_operations",
                        to="catalog.producttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product template operation",
                "verbose_name_plural": "Product template operations",
                "db_table": "product_template_operations",
                "ordering": ["product_template_id", "sequence_order", "operation_type_id"],
            },
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="templates",
                to="catalog.producttype",
            ),
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("width_mm", models.PositiveIntegerField()),
                ("height_mm", models.PositiveIntegerField()),
                ("label_uk", models.CharField(max_length=255)),
                ("label_ru", models.CharField(blank=True, default="", max_length=255)),
                ("label_en", models.CharField(blank=True, default="", max_length=255)),
                ("name_uk", models.CharField(blank=True, default="", max_length=255)),
                ("name_ru", models.CharField(blank=True, default="", max_length=255)),
                ("name_en", models.CharField(blank=True, default="", max_length=255)),
                ("is_vertical", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sizes",
                        to="catalog.producttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Size",
                "verbose_name_plural": "Sizes",
                "db_table": "sizes",
            },
        ),
        migrations.CreateModel(
            name="MaterialAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("alias", models.CharField(db_index=True, max_length=255)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="catalog.material",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material alias",
                "verbose_name_plural": "Material aliases",
                "db_table": "material_aliases",
                "unique_together": {("material", "alias")},
            },
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["category", "active"], name="materials_categor_b1430c_idx"),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["form_factor", "active"], name="materials_form_fa_5fe84b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialoperationcapability",
            index=models.Index(
                fields=["material", "active"], name="material_op_materia_98926c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialoperationcapability",
            index=models.Index(
                fields=["operation_type", "active"], name="material_op_operati_db50c0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="materialoperationcapability",
            constraint=models.UniqueConstraint(
                fields=("material", "operation_type"), name="uq_material_operation_capability"
            ),
        ),
        migrations.AddIndex(
            model_name="producttemplateoperation",
            index=models.Index(
                fields=["product_template", "active"], name="product_tem_product_f4b456_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="producttemplateoperation",
            index=models.Index(
                fields=["operation_type", "active"], name="product_tem_operati_97354b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="producttemplateoperation",
            constraint=models.UniqueConstraint(
                fields=("product_template", "operation_type"), name="uq_product_template_operation"
            ),
        ),
        migrations.AddIndex(
            model_name="producttemplate",
            index=models.Index(
                fields=["product_type", "active"], name="product_tem_product_fe1ff5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="size",
            constraint=models.UniqueConstraint(fields=("code",), name="uq_sizes_code"),
        ),
    ]
