# Generated by Django 5.2.13 on 2026-05-13 11:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "unit",
                    models.CharField(
                        choices=[("item", "Item"), ("sheet", "Sheet"), ("order", "Order")],
                        db_index=True,
                        default="sheet",
                        max_length=16,
                    ),
                ),
                (
                    "waste_percent",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "material",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price",
                        to="catalog.material",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material price",
                "verbose_name_plural": "Material prices",
                "db_table": "material_prices",
                "ordering": ["material__name_uk"],
            },
        ),
        migrations.CreateModel(
            name="OperationPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "setup_price",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("item", "Item"), ("sheet", "Sheet"), ("order", "Order")],
                        db_index=True,
                        default="item",
                        max_length=16,
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "operation_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price",
                        to="catalog.operationtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation price",
                "verbose_name_plural": "Operation prices",
                "db_table": "operation_prices",
                "ordering": [
                    "operation_type__group",
                    "operation_type__sort_order",
                    "operation_type__name_uk",
                ],
            },
        ),
    ]
