# Generated by Django 5.2.13 on 2026-05-14 08:12

from __future__ import annotations

from django.db import migrations


def backfill_i18n_fields(apps, schema_editor):
    specs = [
        ("catalog", "ProductType", "name_uk", "name_i18n", "description", "description_i18n"),
        ("catalog", "MaterialCategory", "name_uk", "name_i18n", "description", "description_i18n"),
        ("catalog", "Material", "name_uk", "name_i18n", None, None),
        ("catalog", "OperationType", "name_uk", "name_i18n", "description", "description_i18n"),
        ("catalog", "ProductTemplate", "name_uk", "name_i18n", "description", "description_i18n"),
    ]

    for app_label, model_name, old_name_field, new_name_field, old_desc_field, new_desc_field in specs:
        model = apps.get_model(app_label, model_name)

        for obj in model.objects.all():
            update_fields: list[str] = []

            current_name_i18n = getattr(obj, new_name_field, None) or {}
            old_name_value = getattr(obj, old_name_field, "") or ""
            if not current_name_i18n and old_name_value:
                setattr(obj, new_name_field, {"uk": old_name_value})
                update_fields.append(new_name_field)

            if old_desc_field and new_desc_field:
                current_desc_i18n = getattr(obj, new_desc_field, None) or {}
                old_desc_value = getattr(obj, old_desc_field, "") or ""
                if not current_desc_i18n and old_desc_value:
                    setattr(obj, new_desc_field, {"uk": old_desc_value})
                    update_fields.append(new_desc_field)

            if update_fields:
                obj.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_material_name_i18n_materialcategory_description_i18n_and_more"),  # <- тут постав generated migration з AddField
    ]

    operations = [
        migrations.RunPython(backfill_i18n_fields, migrations.RunPython.noop),
    ]
