# Generated by Django 5.2.13 on 2026-05-14 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_backfill_i18n_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="UiSkin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("theme_json", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=100)),
            ],
            options={
                "verbose_name": "UI skin",
                "verbose_name_plural": "UI skins",
                "db_table": "ui_skins",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UiBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "region_code",
                    models.CharField(blank=True, db_index=True, default="", max_length=16),
                ),
                ("default_locale", models.CharField(default="en", max_length=16)),
                ("default_currency", models.CharField(default="USD", max_length=8)),
                ("settings_json", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=100)),
                (
                    "default_skin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brands",
                        to="catalog.uiskin",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI brand",
                "verbose_name_plural": "UI brands",
                "db_table": "ui_brands",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UiBrandProductTemplateVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_visible", models.BooleanField(db_index=True, default=True)),
                ("default_enabled", models.BooleanField(db_index=True, default=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=100)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_visibilities",
                        to="catalog.uibrand",
                    ),
                ),
                (
                    "product_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_visibilities",
                        to="catalog.producttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI brand product template visibility",
                "verbose_name_plural": "UI brand product template visibilities",
                "db_table": "ui_brand_product_template_visibilities",
                "ordering": ["brand_id", "sort_order", "product_template_id"],
                "indexes": [
                    models.Index(fields=["brand", "active"], name="ui_brand_pr_brand_i_6b1cee_idx"),
                    models.Index(
                        fields=["product_template", "active"], name="ui_brand_pr_product_5fd2fc_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("brand", "product_template"),
                        name="uq_ui_brand_product_template_visibility",
                    )
                ],
            },
        ),
    ]
