# Generated by Django 5.2.13 on 2026-05-14 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_uiskin_uibrand_uibrandproducttemplatevisibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("external", "External")],
                        db_index=True,
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "brand_code",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "customer_ref",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                (
                    "external_order_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                (
                    "external_customer_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True, unique=True
                    ),
                ),
                ("product_template_code", models.CharField(db_index=True, max_length=64)),
                ("material_code", models.CharField(db_index=True, max_length=64)),
                ("quantity", models.PositiveIntegerField()),
                ("selected_operation_codes_json", models.JSONField(blank=True, default=list)),
                ("locale", models.CharField(default="en", max_length=16)),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("request_payload_json", models.JSONField(blank=True, default=dict)),
                ("normalized_request_json", models.JSONField(blank=True, default=dict)),
                ("human_report_json", models.JSONField(blank=True, default=dict)),
                ("external_report_json", models.JSONField(blank=True, default=dict)),
                (
                    "subtotal",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "total",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("finished_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                "verbose_name": "Calculation job",
                "verbose_name_plural": "Calculation jobs",
                "db_table": "calculation_jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "status", "created_at"],
                        name="calculation_source_1409b8_idx",
                    ),
                    models.Index(
                        fields=["external_order_id", "created_at"],
                        name="calculation_externa_21e649_idx",
                    ),
                    models.Index(
                        fields=["brand_code", "created_at"], name="calculation_brand_c_fe5117_idx"
                    ),
                ],
            },
        ),
    ]
