# Generated by Django 5.2.13 on 2026-05-18 15:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_calculationjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguratorDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("quoted", "Quoted"),
                            ("submitted", "Submitted"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("brand_code", models.CharField(blank=True, default="", max_length=64)),
                ("product_template_code", models.CharField(blank=True, default="", max_length=128)),
                ("material_code", models.CharField(blank=True, default="", max_length=128)),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("selected_operation_codes_json", models.JSONField(blank=True, default=list)),
                ("locale", models.CharField(blank=True, default="", max_length=16)),
                ("currency", models.CharField(blank=True, default="", max_length=8)),
                ("client_meta_json", models.JSONField(blank=True, default=dict)),
                ("state_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "configurator_drafts",
                "ordering": ("-updated_at",),
            },
        ),
    ]
