# Generated by Django 5.2.13 on 2026-05-18 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_configuratordraft"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "source_system",
                    models.CharField(db_index=True, default="library", max_length=32),
                ),
                ("sync_mode", models.CharField(default="full", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="started",
                        max_length=16,
                    ),
                ),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("meta_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "catalog_sync_runs",
                "ordering": ("-started_at",),
            },
        ),
        migrations.AddField(
            model_name="material",
            name="external_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="material",
            name="source_system",
            field=models.CharField(
                choices=[("local", "Local"), ("library", "Library")],
                db_index=True,
                default="local",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="source_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="materialcategory",
            name="external_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="materialcategory",
            name="source_system",
            field=models.CharField(
                choices=[("local", "Local"), ("library", "Library")],
                db_index=True,
                default="local",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="materialcategory",
            name="source_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationtype",
            name="external_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="operationtype",
            name="source_system",
            field=models.CharField(
                choices=[("local", "Local"), ("library", "Library")],
                db_index=True,
                default="local",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="operationtype",
            name="source_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="external_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="source_system",
            field=models.CharField(
                choices=[("local", "Local"), ("library", "Library")],
                db_index=True,
                default="local",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="source_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producttype",
            name="external_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="producttype",
            name="source_system",
            field=models.CharField(
                choices=[("local", "Local"), ("library", "Library")],
                db_index=True,
                default="local",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="source_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uibrand",
            name="external_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="uibrand",
            name="source_system",
            field=models.CharField(
                choices=[("local", "Local"), ("library", "Library")],
                db_index=True,
                default="local",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="uibrand",
            name="source_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CatalogSyncIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=64)),
                (
                    "external_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("message", models.TextField()),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="catalog.catalogsyncrun",
                    ),
                ),
            ],
            options={
                "db_table": "catalog_sync_issues",
                "ordering": ("-created_at",),
            },
        ),
    ]
