# Generated by Django 5.2.13 on 2026-05-19 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_catalogsyncrun_material_external_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpositionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("manual_required", "Manual Required"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("engine_code", models.CharField(blank=True, default="mock", max_length=64)),
                ("layout_mode", models.CharField(blank=True, default="none", max_length=32)),
                ("product_template_code", models.CharField(blank=True, default="", max_length=128)),
                ("material_code", models.CharField(blank=True, default="", max_length=128)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("request_json", models.JSONField(blank=True, default=dict)),
                ("result_json", models.JSONField(blank=True, default=dict)),
                ("input_file_path", models.TextField(blank=True, default="")),
                ("output_file_path", models.TextField(blank=True, default="")),
                ("message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "imposition_jobs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="allowed_layout_modes_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="layout_profile",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("n_up", "N-up"),
                    ("step_repeat", "Step & Repeat"),
                    ("manual", "Manual"),
                ],
                default="none",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="requires_imposition",
            field=models.BooleanField(default=False),
        ),
    ]
