# Generated by Django 5.2.13 on 2026-06-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_impositionjob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuratordraft",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("quoted", "Quoted"), ("submitted", "Submitted")],
                db_index=True,
                default="draft",
                max_length=32,
            ),
        ),
    ]
